[package]
name = "astar-wasm"
version = "0.1.0"
edition = "2021"
authors = ["Tim Pepper <tim@timpepper.dev>"]
description = "A* Search Algorithm WASM implementation"
license = "MIT"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.92"
